resources:
  - name: go_repo
    type: GitRepo
    configuration:
      gitProvider: manokarthi_git
      path: Manokarthi2412/go-sample-pipelines
      branches:
        include: main
pipelines:
  - name: go_pipeline
    steps:
     - name: build_go
       type: GoBuild
       configuration:
         sourceLocation: .
         resolverRepo: quickstart-go-virtual
         noRegistry: true
         inputResources:
           - name: go_repo
         integrations:
           - name: mkartifactory
    #publish go sample 
  - name: publish_go_binary
    type: GoPublishBinary
    configuration:
      inputSteps:
        - name: build_go
      targetRepository: quickstarts-go-local
      integrations:
        - name: mkartifactory
