resources:
  - name: go_repo_validate
    type: GitRepo
    configuration:
      gitProvider: mkGithub
      path: Manokarthi2412/go-sample-pipelines
      branches:
        include: main
pipelines:
  - name: go_pipeline_validate
    steps:
     - name: build_go
       type: GoBuild
       configuration:
         noRegistry: true
         inputResources:
           - name: go_repo_validate
         integrations:
           - name: mkartifactory
    #publish go sample 
- name: publish_go_binary_
    configuration:
      type: GoPublishBinary
      inputSteps:
        - name: build_go
        targetRepository: quickstarts-go-local
        integrations:
          - name: mkartifactory
