resources:
  - name: go_repo_validate
    type: GitRepo
    configuration:
      gitProvider: mkGithub
      path: Manokarthi2412/go-sample-pipelines
      branches:
        include: main
pipelines:
  - name: go_build_validate
    steps:
     - name: go_build
       type: GoBuild
       configuration:
         inputResources:
           - name: go_repo_validate
         integrations:
           - name: mkartifactory
   #----- publish go sample 
  - name: publish_go_binary
    type: GoPublishBinary
    configuration:
      inputSteps:
        - name: go_build
      targetRepository: quickstarts-go-local
      integrations:
        - name: mkartifactory
