resources:
  - name: go_repo_validate
    type: GitRepo
    configuration:
      gitProvider: mkGithub
      path: Manokarthi2412/go-sample-pipelines
      branches:
        include: main

pipelines:
- name: goBuildPipeline
  steps:
  - name: goBuildStep
    type: GoBuild
    configuration:
      inputResources:
      - name: gitRepoResource
      integrations:
      - name: mkartifactory
  - name: goPublishBinaryStep
    type: GoPublishBinary
    configuration:
      targetRepository: go-repo
      autoPublishBuildInfo: true
      forceXrayScan: true
